### PR TITLE
Write fundamentals model

### LINKED ISSUE #9: Implement fundamentals model
Write static model that includes socio-economic variables and draws on past elections' results

### PR DESCRIPTION
**Pull request by AlexAndorra**
Closes #9 

_Ignore the branch name -- this is for the 2022 presidential elections_

- Working version of the fundamentals model: for now, uses only the regional unemployment rate as a predictor. That's good enough, we can do better later on.
- Election results go as far back as 2002, so I tried with the whole history but that's actually not that useful. I found that using the last three national elections (European 2014, President 2017 and European 2019) gave more reasonable posterior predictions.
- Note that this model isn't intended as an accurate retrodiction for past elections (it's actually not). Rather it's a fancy average for each party in each region. It doesn't need to be very precise anyway, as it'll be used as a prior in the dynamic model. The goal is mainly to allow the latter model to have a sense of recent elections and the effect of unemployment.
- I generated posterior predictions with the latest unemployment rate available (Q4 2020). We should update them regularly, when [new rates are released](https://www.insee.fr/fr/statistiques/2012804#tableau-TCRD_025_tab1_regions2016).
- The models need PyMC4, so I updated the `environment.yml` file accordingly (uses the master branch until the first official release)

### CODE REVIEW

**Comment by rlouf** [comment]
Great work! Would you mind adding some text to explain succinctly what you are trying to do with the model and why you moved from one version to the next?

Also, why using the `OrderedMultinomial`? From what I understand here the categories are the political parties; is it correct to assume that there is a natural ordering to them (like there is for e.g. salary ranges)? Would a `Multinomial` give different results?

**Comment by AlexAndorra** [comment]
Thanks for reviewing! It's true the notebook needs explanatory text. However I'm focused on the dynamic model right now and don't have time to document this. Having a first version of the dynamic model will also help framing this notebook in a more useful way. So I suggest merging this, opening an issue to remember to document it, and actually documenting it once the dust settles on the whole model. Does it work for you?

> why using the `OrderedMultinomial`?

It's because there _is_ a natural ordering to the parties: it's harder for people to move from far left to right than from far left to left, so we want to encode that prior information in the model. In contrast, the plain `Multinomial` considers any switch in categories as equally likely. Is that clearer?
For more explanation, you can take a look at chapter 12 of _Statistical Rethinking_, or chapter 15 of _Regression and Other Stories_.

**Comment by rlouf** [comment]
>  So I suggest merging this, opening an issue to remember to document it, and actually documenting it once the dust settles on the whole model. Does it work for you?

If you think that's a better plan, I trust you :)

> > why using the `OrderedMultinomial`?
> 
> 
> 
> It's because there _is_ a natural ordering to the parties: it's harder for people to move from far left to right than from far left to left, 

Makes sense in theory. Although I wouldn't think a priori that the ordering is complete: 

I'd like to see if that assumption makes a difference.

> so we want to encode that prior information in the model. In contrast, the plain `Multinomial` considers any switch in categories as equally likely. Is that clearer?

This implies that people are more likely to go from left to right than the opposite. Is that correct? Or ia there just partial ordering? Do you have any references on the topic?


> For more explanation, you can take a look at chapter 12 of _Statistical Rethinking_, or chapter 15 of _Regression and Other Stories_.

I'm already familiar with treatment of ordinal data.
 Do they discuss politics specifically?

**Comment by AlexAndorra** [comment]
> If you think that's a better plan, I trust you :)

Ha ha thanks, blind trust is always appreciated 😜 

> I'd like to see if that assumption makes a difference.

Definitely, nothing prevents us from testing the model with a plain Multinomial -- we should actually do it, once we have a first stable version.
FWIW, right now my main issue is not that assumption but the drift until Election Day -- where to revert to when there are no polls left? How aggressively?
Once this is fixed we'll have our first stable version 🥳 

> This implies that people are more likely to go from left to right than the opposite. Is that correct?

No, that implies that people are more likely to switch to a category closer to their current than to one that's further away -- i.e more likely to go from left to right than from left to far right; more likely to go from right to far right than from right to left.

>  Do they discuss politics specifically?

McElreath doesn't but Gelman does. In the book he takes Democrat --> Independent --> Republican as an example of ordered categorical data. And he was actually the one who suggested me to try with an ordered likelihood.

**Comment by AlexAndorra** [comment]
Merging, as discussed. I'll add improvements to this as / if needed

**Pull request merged**
