### PR TITLE
First production-ready version of model 🥳

### PR DESCRIPTION
**Pull request by AlexAndorra**
This is ready for review @rlouf 
**See updates below**
Notes:
- ~~This model is good for aggregation but not optimized for prediction yet~~
- It can already be deployed in production
- ~~Focus on `dynamic-aggregator.ipynb` and the python modules (the other notebooks are either old or WIP)~~
- ~~Once Rémi approves these changes, I'll isolate the model into its own python module instead of having it in the notebook~~

My next steps to make this model appropriate for predictions are:

- [x] add popularity and econ variables as predictors
- [x] add pollsters' historical biases 
- [ ] add the number of undecideds to the model
- [x] add the hierarchical structure for past elections
- ~~[ ] develop `MvZeroSumNormal` to estimate the covariance between parties (for now it works -- see commented lines in the model -- but is sub-efficient sampling-wise because the centered parametrization would work better)~~

### CODE REVIEW

**Comment by rlouf** [comment]
I left some comments on ReviewNB, feel free to answer there. Overall it's great, very similar in spirit to the random walk model we discussed except you are using a Gaussian Process in lieu of a random walk. Why not ?

While you answer my questions I'll give the model a test drive on my machine.

**Comment by AlexAndorra** [comment]
Thanks for the thorough review @rlouf !
I addressed some of your questions already and will continue over the weekend. 

WRT random walk, there are at least three reasons:
1) My assumption is that public opinion is not really a random walk -- it's less random and has momentum, which the GP can pick up with the lengthscale, whereas the RW has by definition a very short memory
2) The GP here is optimized for sampling performance thanks to the eigen decomposition (see the very low sample time), whereas RWs tend to require a long time to sample, as there are lots of parameters to estimate
3) I just wanted to play with the GP 😁

**Comment by AlexAndorra** [comment]
UPDATE @rlouf : I made substantial progress on the combined model (polls + fundamentals) and now have the structure ready (see last model of `dynamic-predictive-model.ipynb`).

The Dirichlet-Multinomial likelihood made a big difference by allowing the model to account for overdispersion in the polls (compared to what a classic Multinomial would expect), and makes also more scientific sense: it's much more credible that each poll has its own Multinomial probability vector, sampled from a common distribution of probability vectors, than _all_ the polls having one common probability vector. This basically accounts for observational noise other than house effects (polling error, sampling bias, etc.) and was much needed (compare to the penultimate model for example).

This model is very promising, but I still have to test it on 1 month and 2 months out-of-sample. Then I'll add predictors and this can be deployed 🥳 It'll still be a first version of course, we'll add improvements later one.

PS: I won't be able to work on that next week, I have to focus on another project.

**Comment by AlexAndorra** [comment]
@rlouf this is now officially ready for review 🥳 
I know the PR is _huge_, so you can just look at `presidential-elections/notebooks/dynamic-model-final.ipynb` and `presidential-elections/utils/model_builder.py`, that's where most of the magic happens.

This model is good to deploy, so let's merge ASAP and then you can work on deployment while I come up with a second version of the model.
I already know what I wanna add (force Green at 0 in 2017, expanding variance for GP kernel, add Zemmour), but I'll do that in another PR and am **not gonna touch this PR until it's merged**.

LMK if you wanna have a call to review live -- might be easier. PyMCheers 🖖

**Comment by AlexAndorra** [comment]
As discussed, I've experimented with an RW GP kernel, but no low-hanging fruits -- if that is indeed appropriate, it requires much more care. So I suggest going ahead with this PR, as the model is already in a good state, and refining incrementally when and if necessary. We already have _a lot_ of content to publish with this model.

The two most important remaining improvements to the model are force Green at 0 in 2017 and adding Zemmour. This will be addressed in later PRs

**Comment by rlouf** [comment]
LGTM (besides minor comments in private discussion), great job! Could you do one commit that removes all the stuff that's been commented out in `model_builder.py` so it is easier to read? You can merge without my approval once that's done.

I'll soon share a document with the mathematical description of the model and may add a few comments in the code for people new to the project :sweat_smile:

**Comment by AlexAndorra** [comment]
> Could you do one commit that removes all the stuff that's been commented out in model_builder.py so it is easier to read?

Done

> I'll soon share a document with the mathematical description of the model and may add a few comments in the code for people new to the project

This is super helpful, thanks 🤩 

And thanks for this thorough review! I know it was hard, as the PR was so huge, but you sticked to it and made valuable comments 🙏

**Pull request merged**
